/* This file is only needed to generate the translation keys for the languages used for the translation feature.
    Issue reference: https://github.com/i18next/i18next-parser?tab=readme-ov-file#caveats */
import { useTranslation } from 'react-i18next';

export const languages = () => {
  const { t } = useTranslation();

  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_AR_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_BN_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_CS_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_DA_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_DE_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_EL_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_EN_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_ES_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_FI_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_FR_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_HE_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_HI_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_HU_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_ID_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_IT_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_JA_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_KO_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_NL_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_NO_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_PL_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_PT_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_RO_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_RU_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_SK_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_SV_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_TA_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_TH_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_TR_LABEL');
  t('__TOOLS_TRANSLATE_LANGUAGE_TRANSLATION_ZH_LABEL');
};
