name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_PAT }}

      - name: Bump version and push tag
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.REPO_PAT }}
          git-message: 'chore(release): {version}'

      - uses: ncipollo/release-action@v1
        if: ${{steps.changelog.outputs.skipped == 'false'}}
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          token: ${{ secrets.REPO_PAT }}